//
//  ListModels.swift
//  CleanSwift
//
//  Created by vaishanavi.sasane on 13/08/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List
{
    // MARK: Use cases

    enum ListEntities {
        struct Request {
            let username, password: String
        }
        struct ViewModelSuccess {
            let username: String
            let email: String
            let phone: String
        }
        struct ViewModelFailure {
            let errorMessage: String
        }
    }
}

struct User: Codable {
    let name: String
    let email: String
    let phone: String
}

