//
//  ListPresenter.swift
//  CleanSwift
//
//  Created by vaishanavi.sasane on 13/08/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
    func presentListData(response: [User])
    func presentError(error: List.ListEntities.ViewModelFailure)
}

class ListPresenter: ListPresentationLogic {
    
    weak var viewController: ListDisplayLogic?

    // MARK: Parse and calc respnse from ListInteractor and send simple view model to ListViewController to be displayed

    func presentListData(response: [User]) {
        viewController?.displayUser(viewModel: response)
    }
    
    func presentError(error: List.ListEntities.ViewModelFailure) {
        viewController?.displayFailure(viewModel: error)
    }

}
